#!/usr/bin/env bash

# requires fzf to be installed

shopt -s expand_aliases


COMPOSE=0
if which docker &> /dev/null; then
    if docker compose version &> /dev/null; then
        alias compose="docker compose"
        COMPOSE=1
    elif which docker-compose &> /dev/null; then
        alias compose="docker-compose"
        COMPOSE=1
    fi
elif which podman &> /dev/null; then
    alias compose="podman compose"
    if which docker-compose &> /dev/null ; then
        COMPOSE=1
    elif which podman-compose &> /dev/null; then
        COMPOSE=2
    fi
fi

if [ $COMPOSE -eq 0 ]; then
    echo "docker compose not available";
    exit 1;
fi

function isRunning() {
    if [ $COMPOSE -eq 1 ]; then
        if [[ "$(compose 2>/dev/null ls | grep $1)" == "" ]]; then
            return 0
        fi
        return 1
    fi
    if [[ "$(compose 2>/dev/null -f $1)" == "" ]]; then
        return 0
    fi
    return 1
}

DIR=${DOCKER_CONTAINERS_HOME:-$(dirname "$(readlink -f "$0")")}
cd $DIR

find . -type f -iname "docker-compose*" 2>/dev/null \
    | sed -E 's|^./(.*)$|\1|g' \
    | fzf -m -i --layout=reverse --height="100%" --border=rounded --border-label="Choose service" --info=right --preview='less {}' \
    | while read -r composefile; do
        if ! isRunning "$composefile"; then
            echo "downing $composefile"
            compose -f "$composefile" down
            continue
        fi
        echo "running $composefile"
        compose -f "$composefile" up --build -d
    done

sleep 2

