
services:
  swagger:
    container_name: 'swagger'
    image: swaggerapi/swagger-ui
    restart: on-failure
    volumes:
      - ./swagger-docs:/docs:ro
    ports:
      - 3030:8080
    networks:
      - swagger

networks:
  swagger:
    name: 'swagger'
