version: '3.8'


services:
  mongodb:
    container_name: 'mongodb-replica-1'
    restart: always
    image: "mongo"
      #command: --config /data/configdb/mongod.conf
    command: "--bind_ip_all --keyFile /data/configdb/mongodb.key --replSet rs0"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_INITDB_DATABASE=tr
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - ./data:/data/db
      - ./config:/data/configdb
    networks:
      - mongo_network
  ui:
    container_name: mongodb-ui
    image: mongo-express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 27018:8081
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_network
volumes:
  mongo_data:
    name: mongo_data
  mongo_config:
    name: mongo_config

