version: '3.8'


services:
  mongodb:
    container_name: 'mongodb'
    restart: always
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=tr
    ports:
      - 27017:27017
    healthcheck:
       test: test $$(mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet --eval "db.stats().ok") -eq 1
       interval: 10s
       start_period: 30s
    volumes:
      - ./data:/data/db
      - ./config:/data/configdb
    networks:
      - mongo_network
  ui:
    container_name: mongodb-ui
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 27018:8081
    networks:
      - mongo_network
    depends_on:
      - mongodb

networks:
  mongo_network:
    name: mongo_network

