
services:
  elasticsearch:
    image: elasticsearch:8.0.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - search:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana:8.0.0
    restart: always
    ports:
      - 5601:5601
    networks:
      - elastic
volumes:
  search:

networks:
  elastic:
    name: 'elastic'
