#!/bin/bash

# check if docker-compose file exists
which docker-compose &> /dev/null;
if [ $? -eq 0 ]; then
    docker-compose exec nginx certbot $@;
    exit 0;
fi

# check if dokcer compose plugin exists
docker compose version &> /dev/null;
if [ $? -eq 0 ]; then
    docker compose exec nginx certbot $@;
    exit 0;
fi
echo "docker compose not installed" 1>&2;
exit 1;

