version: '3.8'

services:
  kafka-broker:
    restart: always
    container_name: 'kafka-broker'
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        #KAFKA_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka-broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - broker
      - zookeeper
  zookeeper:
    restart: always
    container_name: 'kafka-zookeeper'
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - zookeeper
  kafka-ui:
    restart: always
    container_name: 'kafka-ui'
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8181:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui.config.yaml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - zookeeper
      - kafka-broker
    networks:
      - zookeeper
      - broker

networks:
    zookeeper:
      name: 'kafka-zookeeper'
    broker:
      name: 'kafka-broker'
