version: '3.8'

services:
  redis:
    restart: always
    container_name: redis
    command: redis-server --port 6379
    image: redis:alpine
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    networks:
      - redis_network 
networks:
  redis_network:
    name: redis_network
