services:
  fake-smtp-server:
    container_name: dev-fake-smtp-server
    image: rnwood/smtp4dev
    restart: on-failure
    ports:
      - "127.0.0.1:3000:80"
      - "127.0.0.1:2525:25"
    networks:
        - smtp-network
networks:
  smtp-network:
    name: smtp-network
